import type { Metadata } from "next";
import { Familjen_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import { getServerSession } from "next-auth";
import authOptions from "@/lib/auth";

const familjenGrotesk = Familjen_Grotesk({
  variable: "--font-familjen-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: any = await getServerSession(authOptions);
  const { user } = session || { user: null };

  return (
    <html lang="pl">
      <body
        className={`${familjenGrotesk.variable} antialiased max-w-[1200px] m-auto`}
      >
        <Header user={user} />
        <div className="px-2 mt-4">{children}</div>
      </body>
    </html>
  );
}
